local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

return {
  s("fmt", {
    t({
      "BasedOnStyle: LLVM",
      "",
      "IndentWidth: 2",
      "TabWidth: 2",
      "UseTab: Never",
      "",
      "ColumnLimit: 80",
      "",
      "PointerAlignment: Left",
      "ReferenceAlignment: Pointer",
      "DerivePointerAlignment: false",
      "",
      "AllowShortIfStatementsOnASingleLine: WithoutElse",
      "",
      "FixNamespaceComments: true",
      "ShortNamespaceLines: 0",
      "",
      "IncludeBlocks: Regroup",
      "",
      "AlignAfterOpenBracket: Align",
      "AlignTrailingComments: true",
      "",
      "MaxEmptyLinesToKeep: 1",
    }),
  }),

  s("tidy", {
    t({
      "Checks: >-",
      "  clang-analyzer-*,",
      "  bugprone-*,",
      "  performance-*,",
      "  modernize-*,",
      "  readability-*,",
      "  cppcoreguidelines-*,",
      "  misc-*,",
      "  -hicpp-*,",
      "  -portability-*,",
      "  -readability-magic-numbers,",
      "  -cppcoreguidelines-avoid-magic-numbers,",
      "  -readability-identifier-naming,",
      "  readability-braces-around-statements",
      "",
      "WarningsAsErrors: ''",
      "HeaderFilterRegex: '.*'",
      "AnalyzeTemporaryDtors: false",
      "FormatStyle: file",
      "",
      "CheckOptions:",
      "  - key: modernize-use-nullptr.NullMacros",
      "    value: 'NULL'",
    }),
  }),
}
