#################
### AUTOSTART ###
#################

exec-once = [workspace 1 silent] ghostty
exec-once = [workspace 2 silent] brave-browser
# exec-once = [workspace 4 silent] discord
exec-once = [workspace 3 silent] spotify-launcher
exec-once = waybar
exec-once = killall -q swww;sleep .5 && swww-daemon
