#################
### AUTOSTART ###
#################

exec-once = helium-browser &
exec-once = ghostty &
exec-once = hypridle &
exec-once = waybar &
exec-once = killall -q awww;sleep .5 && awww-daemon
