#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = colemak_dh_ortho
    # kb_model =
		kb_options = ctrl:nocaps
    # kb_rules =

    repeat_rate = 50
    repeat_delay = 300

    follow_mouse = 2

    accel_profile = 

    sensitivity = -0.90

    touchpad {
        disable_while_typing = false
        natural_scroll = false
        scroll_factor = 0.5
        tap-to-click = false
    }
}

# # https://wiki.hyprland.org/Configuring/Variables/#gestures
# gestures {
#     workspace_swipe = false
# }

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
}

