#############
##u# INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = colemak_dh_ortho
    # kb_model =
		kb_options = ctrl:swapcaps
    # kb_rules =
    
    repeat_rate = 50
    repeat_delay = 300

    follow_mouse = 2

    accel_profile = 

    sensitivity = -0.90
}

cursor {
  no_warps = true
}

# # https://wiki.hyprland.org/Configuring/Variables/#gestures
# gestures {
#     workspace_swipe = false
# }

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
  name = syna2393:00-06cb:7a13-touchpad
  accel_profile = adaptive
  sensitivity = 0.0
  scroll_factor = 0.1
  tap-to-click = false
}

device {
  name = at-translated-set-2-keyboard
  # enabled = false
}
