source = ~/.config/hypr/config/variables.conf

###################
### KEYBINDINGS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main mainModifier

bind = $mainMod, X, killactive,
bind = $mainMod, V, exit,
bind = $mainMod, D, exec, $toggle_rofi
bind = $mainMod, T, exec, $wall_select
bind = $mainMod, SPACE, togglefloating
bind = $mainMod, S, exec, hyprpicker -a
bind = $mainMod, Z, exec, ~/.config/hypr/scripts/toggle_zen

bind = $mainMod, C, exec, grim -g "$(slurp)" - | wl-copy --type image/png
bind = $mainMod SHIFT, C, exec, grim -g "$(slurp)" ~/images/screenshots/ss-$(date +%Y%m%d-%H%M%S).png

bind = $mainMod, A, exec, grim - | wl-copy --type image/png
bind = $mainMod SHIFT, A, exec, grim ~/images/screenshots/ss-$(date +%Y%m%d-%H%M%S).png

# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, Q, workspace, 1
bind = $mainMod, W, workspace, 2
bind = $mainMod, F, workspace, 3
bind = $mainMod, P, workspace, 4
bind = $mainMod, B, workspace, 5

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, Q, movetoworkspacesilent, 1
bind = $mainMod SHIFT, W, movetoworkspacesilent, 2
bind = $mainMod SHIFT, F, movetoworkspacesilent, 3
bind = $mainMod SHIFT, P, movetoworkspacesilent, 4
bind = $mainMod SHIFT, B, movetoworkspacesilent, 5

# Move/resize windows with mainMod + LMB/RMB and dragging
bind = $mainMod, R, submap, fastedit
submap = fastedit

bind = $mainMod, slash, togglesplit, # dwindle

bind = , L, resizeactive, 20 0
bind = , H, resizeactive, -20 0
bind = , K, resizeactive, 0 -20
bind= , J, resizeactive, 0 20

bind = $mainMod, H, movewindow, l
bind = $mainMod, L, movewindow, r
bind = $mainMod, K, movewindow, u
bind = $mainMod, J, movewindow, d

bind = , escape, submap, reset

submap = reset

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
# bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
# bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
# bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
