###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$toggle_rofi = ~/.config/hypr/scripts/toggle_rofi
$wall_select = ~/.config/hypr/scripts/wall_select

