##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
windowrule = workspace 1, match:class com.mitchellh.ghostty 
windowrule = workspace 2, match:class helium
windowrule = workspace 3, match:class gimp
windowrule = workspace 3, match:class Postman
windowrule = workspace 4, match:class Spotify
windowrule = workspace 4, match:class discord
windowrule = workspace 4, match:class com.obsproject.Studio
windowrule = workspace name:obsidian, match:class obsidian
windowrule = float on,match:class apm
windowrule = float on,match:class type-beat

windowrule = opacity 0.60, match:class discord
windowrule = opacity 0.60, match:class sioyek
windowrule = opacity 0.99, match:class obsidian

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize on, match:class .*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
