#!/usr/bin/env bash
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-sessionizer"
CONFIG_FILE="$CONFIG_DIR/tmux-sessionizer.conf"

# config file example
# ------------------------
# # file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf
# # If set this override the default TS_SEARCH_PATHS (~/ ~/personal ~/personal/dev/env/.config)
# TS_SEARCH_PATHS=(~/)
# # If set this add additional search paths to the default TS_SEARCH_PATHS
# # The number prefix is the depth for the Path [OPTIONAL]
# TS_EXTRA_SEARCH_PATHS=(~/ghq:3 ~/Git:3 ~/.config:2)
# # If set this will ignore search paths the default is TS_IGNORE_PATHS()
# TS_IGNORE_PATHS=()
# # if set this override the TS_MAX_DEPTH (1)
# TS_MAX_DEPTH=2
# ------------------------

# test if the config file exists
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
fi

sanity_check() {
    if ! command -v tmux &>/dev/null; then
        echo "tmux is not installed. Please install it first."
        exit 1
    fi

    if ! command -v fzf &>/dev/null; then
        echo "fzf is not installed. Please install it first."
        exit 1
    fi
}

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t "$1"
    else
        tmux switch-client -t "$1"
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

find_local_config() {
    dir="$1"

    while [[ "$dir" != "/" ]]; do
        if [[ -f "$dir/.tmux-sessionizer" ]]; then
            echo "$dir/.tmux-sessionizer"
            return
        fi
        dir=$(dirname "$dir")
    done
}

hydrate() {
    local_conf=$(find_local_config "$2")

    if [[ -n "$local_conf" ]]; then
        tmux send-keys -t "$1" "source $local_conf" C-m
    fi
}

sanity_check

# if TS_SEARCH_PATHS is not set use default
[[ -n "$TS_SEARCH_PATHS" ]] || TS_SEARCH_PATHS=(~/ ~/personal ~/personal/dev/env/.config)

# Add any extra search paths to the TS_SEARCH_PATHS array
# e.g : EXTRA_SEARCH_PATHS=("$HOME/extra1:4" "$HOME/extra2")
# note : Path can be suffixed with :number to limit or extend the depth of the search for the Path

if [[ ${#TS_EXTRA_SEARCH_PATHS[@]} -gt 0 ]]; then
    TS_SEARCH_PATHS+=("${TS_EXTRA_SEARCH_PATHS[@]}")
fi

# if TS_IGNORE_PATHS is not set use default
[[ -n "$TS_IGNORE_PATHS" ]] || TS_IGNORE_PATHS=()

# utility function to find directories
find_dirs() {
    # list TMUX sessions
    current_session=""
    current_path=""
    all_session_paths=()

    if [[ -n "${TMUX}" ]]; then
        current_session=$(tmux display-message -p '#S')
        current_path=$(tmux display-message -p -t "$current_session" '#{session_path}')
    fi

    while IFS= read -r path; do
        all_session_paths+=("$path")
    done < <(tmux list-sessions -F '#{session_path}' 2>/dev/null)

    tmux list-sessions -F "[TMUX] #{session_name}" 2>/dev/null | grep -vFx "[TMUX] $current_session"

    # note: TS_SEARCH_PATHS is an array of paths to search for directories
    # if the path ends with :number, it will search for directories with a max depth of number ;)
    # if there is no number, it will search for directories with a max depth defined by TS_MAX_DEPTH or 1 if not set
    for entry in "${TS_SEARCH_PATHS[@]}"; do
        # Check if entry as :number as suffix then adapt the maxdepth parameter
        if [[ "$entry" =~ ^([^:]+):([0-9]+)$ ]]; then
            path="${BASH_REMATCH[1]}"
            depth="${BASH_REMATCH[2]}"
        else
            path="$entry"
        fi

        if [[ -d "$path" ]]; then
            find "$path" -mindepth 1 -maxdepth "${depth:-${TS_MAX_DEPTH:-1}}" \
                 -path '*/.git' -prune -o -type d -print | grep -vFxf <(printf \
                 "%s\n" "${all_session_paths[@]}") | grep -vFxf <(printf "%s\n" \
                 "${TS_IGNORE_PATHS[@]}")
        fi
    done
}

if [[ $# -eq 1 ]]; then
    selected="$1"
else
    selected=$(find_dirs | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ "$selected" =~ ^\[TMUX\]\ (.+)$ ]]; then
    selected="${BASH_REMATCH[1]}"
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
fi

if ! has_session "$selected_name"; then
    tmux new-session -ds "$selected_name" -c "$selected"
    hydrate "$selected_name" "$selected"
fi

switch_to "$selected_name"
