# defaults
set -g detach-on-destroy off

set -g default-terminal "tmux-256color"
set -gq allow-passthrough on

set -g renumber-windows on
set -g base-index 1
bind c new-window -c '#{pane_current_path}'

# binds
set -g prefix C-a

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key k confirm-before -p "Kill current session? (y/n)" "kill-session -t \"#S\""
bind-key K confirm-before -p "Kill server? (y/n)" "kill-server"

bind-key N run-shell "~/.local/bin/tmux-sessionizer ~/notes"

# bar
set -g status-right '[#S]'
set -g status-left '#{?client_prefix,[⸸],}'

set -g window-status-format '#I:#W'
set -g window-status-current-format '[#I:#W]'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-restore 'R'
set -g @plugin 'tmux-plugins/tmux-continuum'

# LACKLUSTER THEME BEGIN
color_lack="#708090"
color_luster="#deeeed"
color_orange="#ffaa88"
color_green="#789978"
color_blue="#7788AA"
color_red="#aa6666"
color_black="#000000"
color_gray1="#080808"
color_gray2="#191919"
color_gray3="#2a2a2a"
color_gray4="#444444"
color_gray5="#555555"
color_gray6="#7a7a7a"
color_gray7="#aaaaaa"
color_gray8="#cccccc"
color_gray9="#DDDDDD"

# NOTE: color variable expansion only works in double quotes
set-option -g status-fg                     "$color_luster"
set-option -g status-bg                     "$color_gray2"
set-option -g copy-mode-current-match-style "fg=$color_gray1,bg=$color_gray8"
set-option -g copy-mode-match-style         "fg=$color_gray1,bg=$color_gray8"
set-option -g menu-selected-style           "fg=$color_gray1,bg=$color_luster"
set-option -g menu-style                    "fg=$color_luster,bg=$color_gray1"
set-option -g message-style                 "bg=$color_gray6,fg=$color_gray1" # command in vi-insert mode
set-option -g message-command-style         "bg=$color_gray6,fg=$color_gray4" # command in vi-normal mode
set-option -g mode-style                    "bg=$color_gray8,fg=$color_gray1"
set-option -g pane-active-border-style      "fg=$color_gray1"
set-option -g pane-border-lines             "heavy"
set-option -g pane-border-style             "fg=$color_gray1"
set-option -g pane-border-style             "fg=$color_gray5"
set-option -g popup-border-lines            "rounded"
set-option -g status-right-style            "fg=$color_gray8"
set-option -g window-status-current-style   "fg=$color_gray8"
set-option -g window-status-style           "fg=$color_gray6"

# LACKLUSTER THEME END

run '~/.config/tmux/plugins/tpm/tpm'
